/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const MedicineId = IDL.Nat;
export const BatchInput = IDL.Record({
  'qty' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'expiryDate' : Timestamp,
  'batchNumber' : IDL.Text,
  'medicineId' : MedicineId,
});
export const BatchId = IDL.Nat;
export const MedicineBatch = IDL.Record({
  'id' : BatchId,
  'qty' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'expiryDate' : Timestamp,
  'createdAt' : Timestamp,
  'batchNumber' : IDL.Text,
  'medicineId' : MedicineId,
});
export const CustomerInput = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const CustomerId = IDL.Nat;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const DistributorInput = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DistributorId = IDL.Nat;
export const Distributor = IDL.Record({
  'id' : DistributorId,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const GstRate = IDL.Variant({
  'gst5' : IDL.Null,
  'gst12' : IDL.Null,
  'gst18' : IDL.Null,
});
export const MedicineInput = IDL.Record({
  'purchasePrice' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'rackLocation' : IDL.Text,
  'hsnCode' : IDL.Text,
  'genericName' : IDL.Text,
  'barcodeId' : IDL.Opt(IDL.Text),
  'gstRate' : GstRate,
  'unitPrice' : IDL.Nat,
});
export const Medicine = IDL.Record({
  'id' : MedicineId,
  'purchasePrice' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'rackLocation' : IDL.Text,
  'hsnCode' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'genericName' : IDL.Text,
  'barcodeId' : IDL.Opt(IDL.Text),
  'gstRate' : GstRate,
  'unitPrice' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CatalogEntryInput = IDL.Record({
  'stockQty' : IDL.Nat,
  'deliveryDays' : IDL.Nat,
  'hsnCode' : IDL.Text,
  'discountPct' : IDL.Nat,
  'price' : IDL.Nat,
  'medicineName' : IDL.Text,
});
export const LineItemInput = IDL.Record({
  'qty' : IDL.Nat,
  'discountPct' : IDL.Nat,
  'batchId' : BatchId,
  'medicineId' : MedicineId,
});
export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const InvoiceId = IDL.Nat;
export const InvoiceInput = IDL.Record({
  'customerName' : IDL.Text,
  'lineItems' : IDL.Vec(LineItemInput),
  'isReturn' : IDL.Bool,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Opt(CustomerId),
  'originalInvoiceId' : IDL.Opt(InvoiceId),
});
export const InvoiceLineItem = IDL.Record({
  'qty' : IDL.Nat,
  'lineTotal' : IDL.Nat,
  'gstAmount' : IDL.Nat,
  'discountPct' : IDL.Nat,
  'batchNumber' : IDL.Text,
  'gstRate' : GstRate,
  'batchId' : BatchId,
  'unitPrice' : IDL.Nat,
  'medicineId' : MedicineId,
  'medicineName' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'customerName' : IDL.Text,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'isReturn' : IDL.Bool,
  'totalGst' : IDL.Nat,
  'invoiceNumber' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Opt(CustomerId),
  'originalInvoiceId' : IDL.Opt(InvoiceId),
  'subtotal' : IDL.Nat,
});
export const OrderLineInput = IDL.Record({
  'qty' : IDL.Nat,
  'discountPct' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'medicineId' : IDL.Opt(MedicineId),
  'medicineName' : IDL.Text,
});
export const PurchaseOrderInput = IDL.Record({
  'distributorId' : DistributorId,
  'lines' : IDL.Vec(OrderLineInput),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PurchaseOrderLine = IDL.Record({
  'qty' : IDL.Nat,
  'lineTotal' : IDL.Nat,
  'distributorId' : DistributorId,
  'discountPct' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'medicineId' : IDL.Opt(MedicineId),
  'medicineName' : IDL.Text,
});
export const PurchaseOrder = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'distributorName' : IDL.Text,
  'distributorId' : DistributorId,
  'lines' : IDL.Vec(PurchaseOrderLine),
  'updatedAt' : Timestamp,
  'totalAmount' : IDL.Nat,
});
export const ExpiryAlert = IDL.Record({
  'qty' : IDL.Nat,
  'expiryDate' : Timestamp,
  'batchNumber' : IDL.Text,
  'batchId' : BatchId,
  'medicineId' : MedicineId,
  'medicineName' : IDL.Text,
});
export const DateRange = IDL.Record({
  'toTime' : Timestamp,
  'fromTime' : Timestamp,
});
export const GstBreakdown = IDL.Record({
  'taxableAmount' : IDL.Nat,
  'rate' : GstRate,
  'gstAmount' : IDL.Nat,
});
export const LowStockAlert = IDL.Record({
  'threshold' : IDL.Nat,
  'currentStock' : IDL.Nat,
  'medicineId' : MedicineId,
  'medicineName' : IDL.Text,
});
export const PurchaseSummary = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalSpend' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const SalesSummary = IDL.Record({
  'gst18Total' : IDL.Nat,
  'gst5Total' : IDL.Nat,
  'totalGst' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'gst12Total' : IDL.Nat,
  'totalReturns' : IDL.Nat,
  'netRevenue' : IDL.Nat,
  'totalInvoices' : IDL.Nat,
});
export const DistributorOffer = IDL.Record({
  'stockQty' : IDL.Nat,
  'deliveryDays' : IDL.Nat,
  'distributorName' : IDL.Text,
  'distributorId' : DistributorId,
  'score' : IDL.Nat,
  'discountPct' : IDL.Nat,
  'price' : IDL.Nat,
});
export const DistributorCatalogEntry = IDL.Record({
  'stockQty' : IDL.Nat,
  'deliveryDays' : IDL.Nat,
  'hsnCode' : IDL.Text,
  'distributorId' : DistributorId,
  'updatedAt' : Timestamp,
  'discountPct' : IDL.Nat,
  'price' : IDL.Nat,
  'medicineId' : IDL.Opt(MedicineId),
  'medicineName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBatch' : IDL.Func([BatchInput], [MedicineBatch], []),
  'addCustomer' : IDL.Func([CustomerInput], [Customer], []),
  'addDistributor' : IDL.Func([DistributorInput], [Distributor], []),
  'addMedicine' : IDL.Func([MedicineInput], [Medicine], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpsertCatalog' : IDL.Func(
      [DistributorId, IDL.Vec(CatalogEntryInput)],
      [IDL.Nat],
      [],
    ),
  'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
  'createPurchaseOrder' : IDL.Func([PurchaseOrderInput], [PurchaseOrder], []),
  'deleteDistributor' : IDL.Func([DistributorId], [IDL.Bool], []),
  'deleteMedicine' : IDL.Func([MedicineId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getCustomerLedger' : IDL.Func([CustomerId], [IDL.Vec(Invoice)], ['query']),
  'getExpiringBatches' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(MedicineBatch, Medicine))],
      ['query'],
    ),
  'getExpiryAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(ExpiryAlert)], ['query']),
  'getGstBreakdown' : IDL.Func([DateRange], [IDL.Vec(GstBreakdown)], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'getLowStockAlerts' : IDL.Func([], [IDL.Vec(LowStockAlert)], ['query']),
  'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getMedicine' : IDL.Func([MedicineId], [IDL.Opt(Medicine)], ['query']),
  'getPurchaseOrder' : IDL.Func([OrderId], [IDL.Opt(PurchaseOrder)], ['query']),
  'getPurchaseSummary' : IDL.Func([DateRange], [PurchaseSummary], ['query']),
  'getSalesSummary' : IDL.Func([DateRange], [SalesSummary], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBatchesForMedicine' : IDL.Func(
      [MedicineId],
      [IDL.Vec(MedicineBatch)],
      ['query'],
    ),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listDistributors' : IDL.Func([], [IDL.Vec(Distributor)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'listPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'searchDistributorOffers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DistributorOffer)],
      ['query'],
    ),
  'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'updateDistributor' : IDL.Func(
      [DistributorId, DistributorInput],
      [IDL.Opt(Distributor)],
      [],
    ),
  'updateMedicine' : IDL.Func(
      [MedicineId, MedicineInput],
      [IDL.Opt(Medicine)],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus],
      [IDL.Opt(PurchaseOrder)],
      [],
    ),
  'upsertCatalogEntry' : IDL.Func(
      [DistributorId, CatalogEntryInput],
      [DistributorCatalogEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const MedicineId = IDL.Nat;
  const BatchInput = IDL.Record({
    'qty' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'expiryDate' : Timestamp,
    'batchNumber' : IDL.Text,
    'medicineId' : MedicineId,
  });
  const BatchId = IDL.Nat;
  const MedicineBatch = IDL.Record({
    'id' : BatchId,
    'qty' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'expiryDate' : Timestamp,
    'createdAt' : Timestamp,
    'batchNumber' : IDL.Text,
    'medicineId' : MedicineId,
  });
  const CustomerInput = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const CustomerId = IDL.Nat;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const DistributorInput = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DistributorId = IDL.Nat;
  const Distributor = IDL.Record({
    'id' : DistributorId,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GstRate = IDL.Variant({
    'gst5' : IDL.Null,
    'gst12' : IDL.Null,
    'gst18' : IDL.Null,
  });
  const MedicineInput = IDL.Record({
    'purchasePrice' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'rackLocation' : IDL.Text,
    'hsnCode' : IDL.Text,
    'genericName' : IDL.Text,
    'barcodeId' : IDL.Opt(IDL.Text),
    'gstRate' : GstRate,
    'unitPrice' : IDL.Nat,
  });
  const Medicine = IDL.Record({
    'id' : MedicineId,
    'purchasePrice' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'rackLocation' : IDL.Text,
    'hsnCode' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'genericName' : IDL.Text,
    'barcodeId' : IDL.Opt(IDL.Text),
    'gstRate' : GstRate,
    'unitPrice' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CatalogEntryInput = IDL.Record({
    'stockQty' : IDL.Nat,
    'deliveryDays' : IDL.Nat,
    'hsnCode' : IDL.Text,
    'discountPct' : IDL.Nat,
    'price' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  const LineItemInput = IDL.Record({
    'qty' : IDL.Nat,
    'discountPct' : IDL.Nat,
    'batchId' : BatchId,
    'medicineId' : MedicineId,
  });
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const InvoiceId = IDL.Nat;
  const InvoiceInput = IDL.Record({
    'customerName' : IDL.Text,
    'lineItems' : IDL.Vec(LineItemInput),
    'isReturn' : IDL.Bool,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Opt(CustomerId),
    'originalInvoiceId' : IDL.Opt(InvoiceId),
  });
  const InvoiceLineItem = IDL.Record({
    'qty' : IDL.Nat,
    'lineTotal' : IDL.Nat,
    'gstAmount' : IDL.Nat,
    'discountPct' : IDL.Nat,
    'batchNumber' : IDL.Text,
    'gstRate' : GstRate,
    'batchId' : BatchId,
    'unitPrice' : IDL.Nat,
    'medicineId' : MedicineId,
    'medicineName' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'customerName' : IDL.Text,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'isReturn' : IDL.Bool,
    'totalGst' : IDL.Nat,
    'invoiceNumber' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Opt(CustomerId),
    'originalInvoiceId' : IDL.Opt(InvoiceId),
    'subtotal' : IDL.Nat,
  });
  const OrderLineInput = IDL.Record({
    'qty' : IDL.Nat,
    'discountPct' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'medicineId' : IDL.Opt(MedicineId),
    'medicineName' : IDL.Text,
  });
  const PurchaseOrderInput = IDL.Record({
    'distributorId' : DistributorId,
    'lines' : IDL.Vec(OrderLineInput),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PurchaseOrderLine = IDL.Record({
    'qty' : IDL.Nat,
    'lineTotal' : IDL.Nat,
    'distributorId' : DistributorId,
    'discountPct' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'medicineId' : IDL.Opt(MedicineId),
    'medicineName' : IDL.Text,
  });
  const PurchaseOrder = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'distributorName' : IDL.Text,
    'distributorId' : DistributorId,
    'lines' : IDL.Vec(PurchaseOrderLine),
    'updatedAt' : Timestamp,
    'totalAmount' : IDL.Nat,
  });
  const ExpiryAlert = IDL.Record({
    'qty' : IDL.Nat,
    'expiryDate' : Timestamp,
    'batchNumber' : IDL.Text,
    'batchId' : BatchId,
    'medicineId' : MedicineId,
    'medicineName' : IDL.Text,
  });
  const DateRange = IDL.Record({
    'toTime' : Timestamp,
    'fromTime' : Timestamp,
  });
  const GstBreakdown = IDL.Record({
    'taxableAmount' : IDL.Nat,
    'rate' : GstRate,
    'gstAmount' : IDL.Nat,
  });
  const LowStockAlert = IDL.Record({
    'threshold' : IDL.Nat,
    'currentStock' : IDL.Nat,
    'medicineId' : MedicineId,
    'medicineName' : IDL.Text,
  });
  const PurchaseSummary = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalSpend' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const SalesSummary = IDL.Record({
    'gst18Total' : IDL.Nat,
    'gst5Total' : IDL.Nat,
    'totalGst' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'gst12Total' : IDL.Nat,
    'totalReturns' : IDL.Nat,
    'netRevenue' : IDL.Nat,
    'totalInvoices' : IDL.Nat,
  });
  const DistributorOffer = IDL.Record({
    'stockQty' : IDL.Nat,
    'deliveryDays' : IDL.Nat,
    'distributorName' : IDL.Text,
    'distributorId' : DistributorId,
    'score' : IDL.Nat,
    'discountPct' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const DistributorCatalogEntry = IDL.Record({
    'stockQty' : IDL.Nat,
    'deliveryDays' : IDL.Nat,
    'hsnCode' : IDL.Text,
    'distributorId' : DistributorId,
    'updatedAt' : Timestamp,
    'discountPct' : IDL.Nat,
    'price' : IDL.Nat,
    'medicineId' : IDL.Opt(MedicineId),
    'medicineName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBatch' : IDL.Func([BatchInput], [MedicineBatch], []),
    'addCustomer' : IDL.Func([CustomerInput], [Customer], []),
    'addDistributor' : IDL.Func([DistributorInput], [Distributor], []),
    'addMedicine' : IDL.Func([MedicineInput], [Medicine], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpsertCatalog' : IDL.Func(
        [DistributorId, IDL.Vec(CatalogEntryInput)],
        [IDL.Nat],
        [],
      ),
    'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
    'createPurchaseOrder' : IDL.Func([PurchaseOrderInput], [PurchaseOrder], []),
    'deleteDistributor' : IDL.Func([DistributorId], [IDL.Bool], []),
    'deleteMedicine' : IDL.Func([MedicineId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getCustomerLedger' : IDL.Func([CustomerId], [IDL.Vec(Invoice)], ['query']),
    'getExpiringBatches' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(MedicineBatch, Medicine))],
        ['query'],
      ),
    'getExpiryAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(ExpiryAlert)], ['query']),
    'getGstBreakdown' : IDL.Func(
        [DateRange],
        [IDL.Vec(GstBreakdown)],
        ['query'],
      ),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'getLowStockAlerts' : IDL.Func([], [IDL.Vec(LowStockAlert)], ['query']),
    'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getMedicine' : IDL.Func([MedicineId], [IDL.Opt(Medicine)], ['query']),
    'getPurchaseOrder' : IDL.Func(
        [OrderId],
        [IDL.Opt(PurchaseOrder)],
        ['query'],
      ),
    'getPurchaseSummary' : IDL.Func([DateRange], [PurchaseSummary], ['query']),
    'getSalesSummary' : IDL.Func([DateRange], [SalesSummary], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBatchesForMedicine' : IDL.Func(
        [MedicineId],
        [IDL.Vec(MedicineBatch)],
        ['query'],
      ),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listDistributors' : IDL.Func([], [IDL.Vec(Distributor)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'listPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'searchDistributorOffers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DistributorOffer)],
        ['query'],
      ),
    'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'updateDistributor' : IDL.Func(
        [DistributorId, DistributorInput],
        [IDL.Opt(Distributor)],
        [],
      ),
    'updateMedicine' : IDL.Func(
        [MedicineId, MedicineInput],
        [IDL.Opt(Medicine)],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(PurchaseOrder)],
        [],
      ),
    'upsertCatalogEntry' : IDL.Func(
        [DistributorId, CatalogEntryInput],
        [DistributorCatalogEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };