/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BatchId = bigint;
export interface BatchInput {
  'qty' : bigint,
  'purchasePrice' : bigint,
  'expiryDate' : Timestamp,
  'batchNumber' : string,
  'medicineId' : MedicineId,
}
export interface CatalogEntryInput {
  'stockQty' : bigint,
  'deliveryDays' : bigint,
  'hsnCode' : string,
  'discountPct' : bigint,
  'price' : bigint,
  'medicineName' : string,
}
export interface Customer {
  'id' : CustomerId,
  'gstNumber' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'address' : [] | [string],
  'phone' : [] | [string],
}
export type CustomerId = bigint;
export interface CustomerInput {
  'gstNumber' : [] | [string],
  'name' : string,
  'address' : [] | [string],
  'phone' : [] | [string],
}
export interface DateRange { 'toTime' : Timestamp, 'fromTime' : Timestamp }
export interface Distributor {
  'id' : DistributorId,
  'gstNumber' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'isActive' : boolean,
  'email' : [] | [string],
  'address' : string,
  'phone' : string,
}
export interface DistributorCatalogEntry {
  'stockQty' : bigint,
  'deliveryDays' : bigint,
  'hsnCode' : string,
  'distributorId' : DistributorId,
  'updatedAt' : Timestamp,
  'discountPct' : bigint,
  'price' : bigint,
  'medicineId' : [] | [MedicineId],
  'medicineName' : string,
}
export type DistributorId = bigint;
export interface DistributorInput {
  'gstNumber' : [] | [string],
  'name' : string,
  'contactPerson' : string,
  'email' : [] | [string],
  'address' : string,
  'phone' : string,
}
export interface DistributorOffer {
  'stockQty' : bigint,
  'deliveryDays' : bigint,
  'distributorName' : string,
  'distributorId' : DistributorId,
  'score' : bigint,
  'discountPct' : bigint,
  'price' : bigint,
}
export interface ExpiryAlert {
  'qty' : bigint,
  'expiryDate' : Timestamp,
  'batchNumber' : string,
  'batchId' : BatchId,
  'medicineId' : MedicineId,
  'medicineName' : string,
}
export interface GstBreakdown {
  'taxableAmount' : bigint,
  'rate' : GstRate,
  'gstAmount' : bigint,
}
export type GstRate = { 'gst5' : null } |
  { 'gst12' : null } |
  { 'gst18' : null };
export interface Invoice {
  'id' : InvoiceId,
  'customerName' : string,
  'lineItems' : Array<InvoiceLineItem>,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'isReturn' : boolean,
  'totalGst' : bigint,
  'invoiceNumber' : string,
  'totalAmount' : bigint,
  'paymentMode' : PaymentMode,
  'customerId' : [] | [CustomerId],
  'originalInvoiceId' : [] | [InvoiceId],
  'subtotal' : bigint,
}
export type InvoiceId = bigint;
export interface InvoiceInput {
  'customerName' : string,
  'lineItems' : Array<LineItemInput>,
  'isReturn' : boolean,
  'paymentMode' : PaymentMode,
  'customerId' : [] | [CustomerId],
  'originalInvoiceId' : [] | [InvoiceId],
}
export interface InvoiceLineItem {
  'qty' : bigint,
  'lineTotal' : bigint,
  'gstAmount' : bigint,
  'discountPct' : bigint,
  'batchNumber' : string,
  'gstRate' : GstRate,
  'batchId' : BatchId,
  'unitPrice' : bigint,
  'medicineId' : MedicineId,
  'medicineName' : string,
}
export interface LineItemInput {
  'qty' : bigint,
  'discountPct' : bigint,
  'batchId' : BatchId,
  'medicineId' : MedicineId,
}
export interface LowStockAlert {
  'threshold' : bigint,
  'currentStock' : bigint,
  'medicineId' : MedicineId,
  'medicineName' : string,
}
export interface Medicine {
  'id' : MedicineId,
  'purchasePrice' : bigint,
  'lowStockThreshold' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'rackLocation' : string,
  'hsnCode' : string,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'genericName' : string,
  'barcodeId' : [] | [string],
  'gstRate' : GstRate,
  'unitPrice' : bigint,
}
export interface MedicineBatch {
  'id' : BatchId,
  'qty' : bigint,
  'purchasePrice' : bigint,
  'expiryDate' : Timestamp,
  'createdAt' : Timestamp,
  'batchNumber' : string,
  'medicineId' : MedicineId,
}
export type MedicineId = bigint;
export interface MedicineInput {
  'purchasePrice' : bigint,
  'lowStockThreshold' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'rackLocation' : string,
  'hsnCode' : string,
  'genericName' : string,
  'barcodeId' : [] | [string],
  'gstRate' : GstRate,
  'unitPrice' : bigint,
}
export type OrderId = bigint;
export interface OrderLineInput {
  'qty' : bigint,
  'discountPct' : bigint,
  'unitPrice' : bigint,
  'medicineId' : [] | [MedicineId],
  'medicineName' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMode = { 'upi' : null } |
  { 'card' : null } |
  { 'cash' : null };
export interface PurchaseOrder {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'distributorName' : string,
  'distributorId' : DistributorId,
  'lines' : Array<PurchaseOrderLine>,
  'updatedAt' : Timestamp,
  'totalAmount' : bigint,
}
export interface PurchaseOrderInput {
  'distributorId' : DistributorId,
  'lines' : Array<OrderLineInput>,
}
export interface PurchaseOrderLine {
  'qty' : bigint,
  'lineTotal' : bigint,
  'distributorId' : DistributorId,
  'discountPct' : bigint,
  'unitPrice' : bigint,
  'medicineId' : [] | [MedicineId],
  'medicineName' : string,
}
export interface PurchaseSummary {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'totalSpend' : bigint,
  'deliveredOrders' : bigint,
}
export interface SalesSummary {
  'gst18Total' : bigint,
  'gst5Total' : bigint,
  'totalGst' : bigint,
  'totalSales' : bigint,
  'gst12Total' : bigint,
  'totalReturns' : bigint,
  'netRevenue' : bigint,
  'totalInvoices' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBatch' : ActorMethod<[BatchInput], MedicineBatch>,
  'addCustomer' : ActorMethod<[CustomerInput], Customer>,
  'addDistributor' : ActorMethod<[DistributorInput], Distributor>,
  'addMedicine' : ActorMethod<[MedicineInput], Medicine>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpsertCatalog' : ActorMethod<
    [DistributorId, Array<CatalogEntryInput>],
    bigint
  >,
  'createInvoice' : ActorMethod<[InvoiceInput], Invoice>,
  'createPurchaseOrder' : ActorMethod<[PurchaseOrderInput], PurchaseOrder>,
  'deleteDistributor' : ActorMethod<[DistributorId], boolean>,
  'deleteMedicine' : ActorMethod<[MedicineId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getCustomerLedger' : ActorMethod<[CustomerId], Array<Invoice>>,
  'getExpiringBatches' : ActorMethod<
    [bigint],
    Array<[MedicineBatch, Medicine]>
  >,
  'getExpiryAlerts' : ActorMethod<[bigint], Array<ExpiryAlert>>,
  'getGstBreakdown' : ActorMethod<[DateRange], Array<GstBreakdown>>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [Invoice]>,
  'getLowStockAlerts' : ActorMethod<[], Array<LowStockAlert>>,
  'getLowStockMedicines' : ActorMethod<[], Array<Medicine>>,
  'getMedicine' : ActorMethod<[MedicineId], [] | [Medicine]>,
  'getPurchaseOrder' : ActorMethod<[OrderId], [] | [PurchaseOrder]>,
  'getPurchaseSummary' : ActorMethod<[DateRange], PurchaseSummary>,
  'getSalesSummary' : ActorMethod<[DateRange], SalesSummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBatchesForMedicine' : ActorMethod<[MedicineId], Array<MedicineBatch>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listDistributors' : ActorMethod<[], Array<Distributor>>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
  'listMedicines' : ActorMethod<[], Array<Medicine>>,
  'listPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'searchDistributorOffers' : ActorMethod<[string], Array<DistributorOffer>>,
  'searchMedicines' : ActorMethod<[string], Array<Medicine>>,
  'updateDistributor' : ActorMethod<
    [DistributorId, DistributorInput],
    [] | [Distributor]
  >,
  'updateMedicine' : ActorMethod<[MedicineId, MedicineInput], [] | [Medicine]>,
  'updateOrderStatus' : ActorMethod<
    [OrderId, OrderStatus],
    [] | [PurchaseOrder]
  >,
  'upsertCatalogEntry' : ActorMethod<
    [DistributorId, CatalogEntryInput],
    DistributorCatalogEntry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];