/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InvoiceInput {
    customerName: string;
    lineItems: Array<LineItemInput>;
    isReturn: boolean;
    paymentMode: PaymentMode;
    customerId?: CustomerId;
    originalInvoiceId?: InvoiceId;
}
export interface OrderLineInput {
    qty: bigint;
    discountPct: bigint;
    unitPrice: bigint;
    medicineId?: MedicineId;
    medicineName: string;
}
export type Timestamp = bigint;
export type OrderId = bigint;
export interface MedicineInput {
    purchasePrice: bigint;
    lowStockThreshold: bigint;
    stockQty: bigint;
    name: string;
    rackLocation: string;
    hsnCode: string;
    genericName: string;
    barcodeId?: string;
    gstRate: GstRate;
    unitPrice: bigint;
}
export interface SalesSummary {
    gst18Total: bigint;
    gst5Total: bigint;
    totalGst: bigint;
    totalSales: bigint;
    gst12Total: bigint;
    totalReturns: bigint;
    netRevenue: bigint;
    totalInvoices: bigint;
}
export type BatchId = bigint;
export interface CustomerInput {
    gstNumber?: string;
    name: string;
    address?: string;
    phone?: string;
}
export interface BatchInput {
    qty: bigint;
    purchasePrice: bigint;
    expiryDate: Timestamp;
    batchNumber: string;
    medicineId: MedicineId;
}
export interface CatalogEntryInput {
    stockQty: bigint;
    deliveryDays: bigint;
    hsnCode: string;
    discountPct: bigint;
    price: bigint;
    medicineName: string;
}
export interface DistributorInput {
    gstNumber?: string;
    name: string;
    contactPerson: string;
    email?: string;
    address: string;
    phone: string;
}
export interface DistributorOffer {
    stockQty: bigint;
    deliveryDays: bigint;
    distributorName: string;
    distributorId: DistributorId;
    score: bigint;
    discountPct: bigint;
    price: bigint;
}
export type MedicineId = bigint;
export interface ExpiryAlert {
    qty: bigint;
    expiryDate: Timestamp;
    batchNumber: string;
    batchId: BatchId;
    medicineId: MedicineId;
    medicineName: string;
}
export interface Medicine {
    id: MedicineId;
    purchasePrice: bigint;
    lowStockThreshold: bigint;
    stockQty: bigint;
    name: string;
    createdAt: Timestamp;
    rackLocation: string;
    hsnCode: string;
    isActive: boolean;
    updatedAt: Timestamp;
    genericName: string;
    barcodeId?: string;
    gstRate: GstRate;
    unitPrice: bigint;
}
export interface PurchaseOrder {
    id: OrderId;
    status: OrderStatus;
    createdAt: Timestamp;
    createdBy: UserId;
    distributorName: string;
    distributorId: DistributorId;
    lines: Array<PurchaseOrderLine>;
    updatedAt: Timestamp;
    totalAmount: bigint;
}
export interface LineItemInput {
    qty: bigint;
    discountPct: bigint;
    batchId: BatchId;
    medicineId: MedicineId;
}
export interface DistributorCatalogEntry {
    stockQty: bigint;
    deliveryDays: bigint;
    hsnCode: string;
    distributorId: DistributorId;
    updatedAt: Timestamp;
    discountPct: bigint;
    price: bigint;
    medicineId?: MedicineId;
    medicineName: string;
}
export interface PurchaseOrderInput {
    distributorId: DistributorId;
    lines: Array<OrderLineInput>;
}
export interface Distributor {
    id: DistributorId;
    gstNumber?: string;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    isActive: boolean;
    email?: string;
    address: string;
    phone: string;
}
export interface Invoice {
    id: InvoiceId;
    customerName: string;
    lineItems: Array<InvoiceLineItem>;
    createdAt: Timestamp;
    createdBy: UserId;
    isReturn: boolean;
    totalGst: bigint;
    invoiceNumber: string;
    totalAmount: bigint;
    paymentMode: PaymentMode;
    customerId?: CustomerId;
    originalInvoiceId?: InvoiceId;
    subtotal: bigint;
}
export interface Customer {
    id: CustomerId;
    gstNumber?: string;
    name: string;
    createdAt: Timestamp;
    address?: string;
    phone?: string;
}
export interface PurchaseOrderLine {
    qty: bigint;
    lineTotal: bigint;
    distributorId: DistributorId;
    discountPct: bigint;
    unitPrice: bigint;
    medicineId?: MedicineId;
    medicineName: string;
}
export type UserId = Principal;
export interface DateRange {
    toTime: Timestamp;
    fromTime: Timestamp;
}
export type DistributorId = bigint;
export type CustomerId = bigint;
export type InvoiceId = bigint;
export interface MedicineBatch {
    id: BatchId;
    qty: bigint;
    purchasePrice: bigint;
    expiryDate: Timestamp;
    createdAt: Timestamp;
    batchNumber: string;
    medicineId: MedicineId;
}
export interface LowStockAlert {
    threshold: bigint;
    currentStock: bigint;
    medicineId: MedicineId;
    medicineName: string;
}
export interface PurchaseSummary {
    totalOrders: bigint;
    pendingOrders: bigint;
    totalSpend: bigint;
    deliveredOrders: bigint;
}
export interface InvoiceLineItem {
    qty: bigint;
    lineTotal: bigint;
    gstAmount: bigint;
    discountPct: bigint;
    batchNumber: string;
    gstRate: GstRate;
    batchId: BatchId;
    unitPrice: bigint;
    medicineId: MedicineId;
    medicineName: string;
}
export interface GstBreakdown {
    taxableAmount: bigint;
    rate: GstRate;
    gstAmount: bigint;
}
export enum GstRate {
    gst5 = "gst5",
    gst12 = "gst12",
    gst18 = "gst18"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMode {
    upi = "upi",
    card = "card",
    cash = "cash"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addBatch(input: BatchInput): Promise<MedicineBatch>;
    addCustomer(input: CustomerInput): Promise<Customer>;
    addDistributor(input: DistributorInput): Promise<Distributor>;
    addMedicine(input: MedicineInput): Promise<Medicine>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpsertCatalog(distributorId: DistributorId, entries: Array<CatalogEntryInput>): Promise<bigint>;
    createInvoice(input: InvoiceInput): Promise<Invoice>;
    createPurchaseOrder(input: PurchaseOrderInput): Promise<PurchaseOrder>;
    deleteDistributor(id: DistributorId): Promise<boolean>;
    deleteMedicine(id: MedicineId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: CustomerId): Promise<Customer | null>;
    getCustomerLedger(customerId: CustomerId): Promise<Array<Invoice>>;
    getExpiringBatches(withinDays: bigint): Promise<Array<[MedicineBatch, Medicine]>>;
    getExpiryAlerts(withinDays: bigint): Promise<Array<ExpiryAlert>>;
    getGstBreakdown(range: DateRange): Promise<Array<GstBreakdown>>;
    getInvoice(id: InvoiceId): Promise<Invoice | null>;
    getLowStockAlerts(): Promise<Array<LowStockAlert>>;
    getLowStockMedicines(): Promise<Array<Medicine>>;
    getMedicine(id: MedicineId): Promise<Medicine | null>;
    getPurchaseOrder(id: OrderId): Promise<PurchaseOrder | null>;
    getPurchaseSummary(range: DateRange): Promise<PurchaseSummary>;
    getSalesSummary(range: DateRange): Promise<SalesSummary>;
    isCallerAdmin(): Promise<boolean>;
    listBatchesForMedicine(medicineId: MedicineId): Promise<Array<MedicineBatch>>;
    listCustomers(): Promise<Array<Customer>>;
    listDistributors(): Promise<Array<Distributor>>;
    listInvoices(): Promise<Array<Invoice>>;
    listMedicines(): Promise<Array<Medicine>>;
    listPurchaseOrders(): Promise<Array<PurchaseOrder>>;
    searchDistributorOffers(medicineName: string): Promise<Array<DistributorOffer>>;
    searchMedicines(term: string): Promise<Array<Medicine>>;
    updateDistributor(id: DistributorId, input: DistributorInput): Promise<Distributor | null>;
    updateMedicine(id: MedicineId, input: MedicineInput): Promise<Medicine | null>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<PurchaseOrder | null>;
    upsertCatalogEntry(distributorId: DistributorId, input: CatalogEntryInput): Promise<DistributorCatalogEntry>;
}
import type { BatchId as _BatchId, Customer as _Customer, CustomerId as _CustomerId, CustomerInput as _CustomerInput, Distributor as _Distributor, DistributorCatalogEntry as _DistributorCatalogEntry, DistributorId as _DistributorId, DistributorInput as _DistributorInput, GstBreakdown as _GstBreakdown, GstRate as _GstRate, Invoice as _Invoice, InvoiceId as _InvoiceId, InvoiceInput as _InvoiceInput, InvoiceLineItem as _InvoiceLineItem, LineItemInput as _LineItemInput, Medicine as _Medicine, MedicineBatch as _MedicineBatch, MedicineId as _MedicineId, MedicineInput as _MedicineInput, OrderId as _OrderId, OrderLineInput as _OrderLineInput, OrderStatus as _OrderStatus, PaymentMode as _PaymentMode, PurchaseOrder as _PurchaseOrder, PurchaseOrderInput as _PurchaseOrderInput, PurchaseOrderLine as _PurchaseOrderLine, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addBatch(arg0: BatchInput): Promise<MedicineBatch> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatch(arg0);
            return result;
        }
    }
    async addCustomer(arg0: CustomerInput): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(to_candid_CustomerInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Customer_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(to_candid_CustomerInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Customer_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDistributor(arg0: DistributorInput): Promise<Distributor> {
        if (this.processError) {
            try {
                const result = await this.actor.addDistributor(to_candid_DistributorInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Distributor_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDistributor(to_candid_DistributorInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Distributor_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMedicine(arg0: MedicineInput): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(to_candid_MedicineInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Medicine_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(to_candid_MedicineInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Medicine_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpsertCatalog(arg0: DistributorId, arg1: Array<CatalogEntryInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpsertCatalog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpsertCatalog(arg0, arg1);
            return result;
        }
    }
    async createInvoice(arg0: InvoiceInput): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_InvoiceInput_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Invoice_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_InvoiceInput_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Invoice_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPurchaseOrder(arg0: PurchaseOrderInput): Promise<PurchaseOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseOrder(to_candid_PurchaseOrderInput_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PurchaseOrder_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseOrder(to_candid_PurchaseOrderInput_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PurchaseOrder_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDistributor(arg0: DistributorId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDistributor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDistributor(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: MedicineId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerLedger(arg0: CustomerId): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerLedger(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerLedger(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpiringBatches(arg0: bigint): Promise<Array<[MedicineBatch, Medicine]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiringBatches(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiringBatches(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpiryAlerts(arg0: bigint): Promise<Array<ExpiryAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiryAlerts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiryAlerts(arg0);
            return result;
        }
    }
    async getGstBreakdown(arg0: DateRange): Promise<Array<GstBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGstBreakdown(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGstBreakdown(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockAlerts(): Promise<Array<LowStockAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockAlerts();
            return result;
        }
    }
    async getLowStockMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockMedicines();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockMedicines();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicine(arg0: MedicineId): Promise<Medicine | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicine(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicine(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseOrder(arg0: OrderId): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseOrder(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseOrder(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseSummary(arg0: DateRange): Promise<PurchaseSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseSummary(arg0);
            return result;
        }
    }
    async getSalesSummary(arg0: DateRange): Promise<SalesSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesSummary(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBatchesForMedicine(arg0: MedicineId): Promise<Array<MedicineBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBatchesForMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBatchesForMedicine(arg0);
            return result;
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDistributors(): Promise<Array<Distributor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDistributors();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDistributors();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMedicines();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMedicines();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPurchaseOrders(): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPurchaseOrders();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPurchaseOrders();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchDistributorOffers(arg0: string): Promise<Array<DistributorOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDistributorOffers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDistributorOffers(arg0);
            return result;
        }
    }
    async searchMedicines(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMedicines(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMedicines(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDistributor(arg0: DistributorId, arg1: DistributorInput): Promise<Distributor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDistributor(arg0, to_candid_DistributorInput_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDistributor(arg0, to_candid_DistributorInput_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMedicine(arg0: MedicineId, arg1: MedicineInput): Promise<Medicine | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, to_candid_MedicineInput_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, to_candid_MedicineInput_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n63(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n63(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertCatalogEntry(arg0: DistributorId, arg1: CatalogEntryInput): Promise<DistributorCatalogEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertCatalogEntry(arg0, arg1);
                return from_candid_DistributorCatalogEntry_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertCatalogEntry(arg0, arg1);
            return from_candid_DistributorCatalogEntry_n65(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Customer_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DistributorCatalogEntry_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DistributorCatalogEntry): DistributorCatalogEntry {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_Distributor_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Distributor): Distributor {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GstBreakdown_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GstBreakdown): GstBreakdown {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_GstRate_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GstRate): GstRate {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceLineItem_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceLineItem): InvoiceLineItem {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Medicine_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medicine): Medicine {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrderLine_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrderLine): PurchaseOrderLine {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrder_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrder): PurchaseOrder {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerId]): CustomerId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceId]): InvoiceId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MedicineId]): MedicineId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Medicine]): Medicine | null {
    return value.length === 0 ? null : from_candid_Medicine_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PurchaseOrder]): PurchaseOrder | null {
    return value.length === 0 ? null : from_candid_PurchaseOrder_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Distributor]): Distributor | null {
    return value.length === 0 ? null : from_candid_Distributor_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MedicineId;
    purchasePrice: bigint;
    lowStockThreshold: bigint;
    stockQty: bigint;
    name: string;
    createdAt: _Timestamp;
    rackLocation: string;
    hsnCode: string;
    isActive: boolean;
    updatedAt: _Timestamp;
    genericName: string;
    barcodeId: [] | [string];
    gstRate: _GstRate;
    unitPrice: bigint;
}): {
    id: MedicineId;
    purchasePrice: bigint;
    lowStockThreshold: bigint;
    stockQty: bigint;
    name: string;
    createdAt: Timestamp;
    rackLocation: string;
    hsnCode: string;
    isActive: boolean;
    updatedAt: Timestamp;
    genericName: string;
    barcodeId?: string;
    gstRate: GstRate;
    unitPrice: bigint;
} {
    return {
        id: value.id,
        purchasePrice: value.purchasePrice,
        lowStockThreshold: value.lowStockThreshold,
        stockQty: value.stockQty,
        name: value.name,
        createdAt: value.createdAt,
        rackLocation: value.rackLocation,
        hsnCode: value.hsnCode,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        genericName: value.genericName,
        barcodeId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.barcodeId)),
        gstRate: from_candid_GstRate_n16(_uploadFile, _downloadFile, value.gstRate),
        unitPrice: value.unitPrice
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InvoiceId;
    customerName: string;
    lineItems: Array<_InvoiceLineItem>;
    createdAt: _Timestamp;
    createdBy: _UserId;
    isReturn: boolean;
    totalGst: bigint;
    invoiceNumber: string;
    totalAmount: bigint;
    paymentMode: _PaymentMode;
    customerId: [] | [_CustomerId];
    originalInvoiceId: [] | [_InvoiceId];
    subtotal: bigint;
}): {
    id: InvoiceId;
    customerName: string;
    lineItems: Array<InvoiceLineItem>;
    createdAt: Timestamp;
    createdBy: UserId;
    isReturn: boolean;
    totalGst: bigint;
    invoiceNumber: string;
    totalAmount: bigint;
    paymentMode: PaymentMode;
    customerId?: CustomerId;
    originalInvoiceId?: InvoiceId;
    subtotal: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        lineItems: from_candid_vec_n26(_uploadFile, _downloadFile, value.lineItems),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        isReturn: value.isReturn,
        totalGst: value.totalGst,
        invoiceNumber: value.invoiceNumber,
        totalAmount: value.totalAmount,
        paymentMode: from_candid_PaymentMode_n29(_uploadFile, _downloadFile, value.paymentMode),
        customerId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.customerId)),
        originalInvoiceId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.originalInvoiceId)),
        subtotal: value.subtotal
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    lineTotal: bigint;
    gstAmount: bigint;
    discountPct: bigint;
    batchNumber: string;
    gstRate: _GstRate;
    batchId: _BatchId;
    unitPrice: bigint;
    medicineId: _MedicineId;
    medicineName: string;
}): {
    qty: bigint;
    lineTotal: bigint;
    gstAmount: bigint;
    discountPct: bigint;
    batchNumber: string;
    gstRate: GstRate;
    batchId: BatchId;
    unitPrice: bigint;
    medicineId: MedicineId;
    medicineName: string;
} {
    return {
        qty: value.qty,
        lineTotal: value.lineTotal,
        gstAmount: value.gstAmount,
        discountPct: value.discountPct,
        batchNumber: value.batchNumber,
        gstRate: from_candid_GstRate_n16(_uploadFile, _downloadFile, value.gstRate),
        batchId: value.batchId,
        unitPrice: value.unitPrice,
        medicineId: value.medicineId,
        medicineName: value.medicineName
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    createdAt: _Timestamp;
    createdBy: _UserId;
    distributorName: string;
    distributorId: _DistributorId;
    lines: Array<_PurchaseOrderLine>;
    updatedAt: _Timestamp;
    totalAmount: bigint;
}): {
    id: OrderId;
    status: OrderStatus;
    createdAt: Timestamp;
    createdBy: UserId;
    distributorName: string;
    distributorId: DistributorId;
    lines: Array<PurchaseOrderLine>;
    updatedAt: Timestamp;
    totalAmount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n40(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        distributorName: value.distributorName,
        distributorId: value.distributorId,
        lines: from_candid_vec_n42(_uploadFile, _downloadFile, value.lines),
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CustomerId;
    gstNumber: [] | [string];
    name: string;
    createdAt: _Timestamp;
    address: [] | [string];
    phone: [] | [string];
}): {
    id: CustomerId;
    gstNumber?: string;
    name: string;
    createdAt: Timestamp;
    address?: string;
    phone?: string;
} {
    return {
        id: value.id,
        gstNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.gstNumber)),
        name: value.name,
        createdAt: value.createdAt,
        address: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.address)),
        phone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    lineTotal: bigint;
    distributorId: _DistributorId;
    discountPct: bigint;
    unitPrice: bigint;
    medicineId: [] | [_MedicineId];
    medicineName: string;
}): {
    qty: bigint;
    lineTotal: bigint;
    distributorId: DistributorId;
    discountPct: bigint;
    unitPrice: bigint;
    medicineId?: MedicineId;
    medicineName: string;
} {
    return {
        qty: value.qty,
        lineTotal: value.lineTotal,
        distributorId: value.distributorId,
        discountPct: value.discountPct,
        unitPrice: value.unitPrice,
        medicineId: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.medicineId)),
        medicineName: value.medicineName
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxableAmount: bigint;
    rate: _GstRate;
    gstAmount: bigint;
}): {
    taxableAmount: bigint;
    rate: GstRate;
    gstAmount: bigint;
} {
    return {
        taxableAmount: value.taxableAmount,
        rate: from_candid_GstRate_n16(_uploadFile, _downloadFile, value.rate),
        gstAmount: value.gstAmount
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockQty: bigint;
    deliveryDays: bigint;
    hsnCode: string;
    distributorId: _DistributorId;
    updatedAt: _Timestamp;
    discountPct: bigint;
    price: bigint;
    medicineId: [] | [_MedicineId];
    medicineName: string;
}): {
    stockQty: bigint;
    deliveryDays: bigint;
    hsnCode: string;
    distributorId: DistributorId;
    updatedAt: Timestamp;
    discountPct: bigint;
    price: bigint;
    medicineId?: MedicineId;
    medicineName: string;
} {
    return {
        stockQty: value.stockQty,
        deliveryDays: value.deliveryDays,
        hsnCode: value.hsnCode,
        distributorId: value.distributorId,
        updatedAt: value.updatedAt,
        discountPct: value.discountPct,
        price: value.price,
        medicineId: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.medicineId)),
        medicineName: value.medicineName
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DistributorId;
    gstNumber: [] | [string];
    name: string;
    createdAt: _Timestamp;
    contactPerson: string;
    isActive: boolean;
    email: [] | [string];
    address: string;
    phone: string;
}): {
    id: DistributorId;
    gstNumber?: string;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    isActive: boolean;
    email?: string;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        gstNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.gstNumber)),
        name: value.name,
        createdAt: value.createdAt,
        contactPerson: value.contactPerson,
        isActive: value.isActive,
        email: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.email)),
        address: value.address,
        phone: value.phone
    };
}
function from_candid_tuple_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_MedicineBatch, _Medicine]): [MedicineBatch, Medicine] {
    return [
        value[0],
        from_candid_Medicine_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gst5: null;
} | {
    gst12: null;
} | {
    gst18: null;
}): GstRate {
    return "gst5" in value ? GstRate.gst5 : "gst12" in value ? GstRate.gst12 : "gst18" in value ? GstRate.gst18 : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
}): PaymentMode {
    return "upi" in value ? PaymentMode.upi : "card" in value ? PaymentMode.card : "cash" in value ? PaymentMode.cash : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceLineItem>): Array<InvoiceLineItem> {
    return value.map((x)=>from_candid_InvoiceLineItem_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseOrderLine>): Array<PurchaseOrderLine> {
    return value.map((x)=>from_candid_PurchaseOrderLine_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_MedicineBatch, _Medicine]>): Array<[MedicineBatch, Medicine]> {
    return value.map((x)=>from_candid_tuple_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GstBreakdown>): Array<GstBreakdown> {
    return value.map((x)=>from_candid_GstBreakdown_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medicine>): Array<Medicine> {
    return value.map((x)=>from_candid_Medicine_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Distributor>): Array<Distributor> {
    return value.map((x)=>from_candid_Distributor_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseOrder>): Array<PurchaseOrder> {
    return value.map((x)=>from_candid_PurchaseOrder_n38(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInput): _CustomerInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DistributorInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DistributorInput): _DistributorInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_GstRate_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GstRate): _GstRate {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceInput): _InvoiceInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_MedicineInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicineInput): _MedicineInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OrderLineInput_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderLineInput): _OrderLineInput {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PurchaseOrderInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseOrderInput): _PurchaseOrderInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    purchasePrice: bigint;
    lowStockThreshold: bigint;
    stockQty: bigint;
    name: string;
    rackLocation: string;
    hsnCode: string;
    genericName: string;
    barcodeId?: string;
    gstRate: GstRate;
    unitPrice: bigint;
}): {
    purchasePrice: bigint;
    lowStockThreshold: bigint;
    stockQty: bigint;
    name: string;
    rackLocation: string;
    hsnCode: string;
    genericName: string;
    barcodeId: [] | [string];
    gstRate: _GstRate;
    unitPrice: bigint;
} {
    return {
        purchasePrice: value.purchasePrice,
        lowStockThreshold: value.lowStockThreshold,
        stockQty: value.stockQty,
        name: value.name,
        rackLocation: value.rackLocation,
        hsnCode: value.hsnCode,
        genericName: value.genericName,
        barcodeId: value.barcodeId ? candid_some(value.barcodeId) : candid_none(),
        gstRate: to_candid_GstRate_n12(_uploadFile, _downloadFile, value.gstRate),
        unitPrice: value.unitPrice
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstNumber?: string;
    name: string;
    address?: string;
    phone?: string;
}): {
    gstNumber: [] | [string];
    name: string;
    address: [] | [string];
    phone: [] | [string];
} {
    return {
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    lineItems: Array<LineItemInput>;
    isReturn: boolean;
    paymentMode: PaymentMode;
    customerId?: CustomerId;
    originalInvoiceId?: InvoiceId;
}): {
    customerName: string;
    lineItems: Array<_LineItemInput>;
    isReturn: boolean;
    paymentMode: _PaymentMode;
    customerId: [] | [_CustomerId];
    originalInvoiceId: [] | [_InvoiceId];
} {
    return {
        customerName: value.customerName,
        lineItems: value.lineItems,
        isReturn: value.isReturn,
        paymentMode: to_candid_PaymentMode_n22(_uploadFile, _downloadFile, value.paymentMode),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        originalInvoiceId: value.originalInvoiceId ? candid_some(value.originalInvoiceId) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distributorId: DistributorId;
    lines: Array<OrderLineInput>;
}): {
    distributorId: _DistributorId;
    lines: Array<_OrderLineInput>;
} {
    return {
        distributorId: value.distributorId,
        lines: to_candid_vec_n35(_uploadFile, _downloadFile, value.lines)
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    discountPct: bigint;
    unitPrice: bigint;
    medicineId?: MedicineId;
    medicineName: string;
}): {
    qty: bigint;
    discountPct: bigint;
    unitPrice: bigint;
    medicineId: [] | [_MedicineId];
    medicineName: string;
} {
    return {
        qty: value.qty,
        discountPct: value.discountPct,
        unitPrice: value.unitPrice,
        medicineId: value.medicineId ? candid_some(value.medicineId) : candid_none(),
        medicineName: value.medicineName
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstNumber?: string;
    name: string;
    contactPerson: string;
    email?: string;
    address: string;
    phone: string;
}): {
    gstNumber: [] | [string];
    name: string;
    contactPerson: string;
    email: [] | [string];
    address: string;
    phone: string;
} {
    return {
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        contactPerson: value.contactPerson,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address,
        phone: value.phone
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GstRate): {
    gst5: null;
} | {
    gst12: null;
} | {
    gst18: null;
} {
    return value == GstRate.gst5 ? {
        gst5: null
    } : value == GstRate.gst12 ? {
        gst12: null
    } : value == GstRate.gst18 ? {
        gst18: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMode.upi ? {
        upi: null
    } : value == PaymentMode.card ? {
        card: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderLineInput>): Array<_OrderLineInput> {
    return value.map((x)=>to_candid_OrderLineInput_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
